INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(FREETYPE_INCLUDE_DIRS ft2build.h
  PATH_SUFFIXES include
  PATHS
  ${CMAKE_SOURCE_DIR}/vendor/*
)

#MESSAGE("FREETYPE_INCLUDE_DIRS is ${FREETYPE_INCLUDE_DIRS}")

FIND_LIBRARY(FREETYPE_LIBRARIES
  NAMES freetype
  PATH_SUFFIXES lib64 lib lib32
  PATHS
  ${CMAKE_SOURCE_DIR}/vendor/*
)

#MESSAGE("FREETYPE_LIBRARIES is ${FREETYPE_LIBRARIES}")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(FREETYPE DEFAULT_MSG
                                  FREETYPE_LIBRARIES
                                  FREETYPE_INCLUDE_DIRS)
