INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GLEW_INCLUDE_DIRS GL/glew.h
  PATH_SUFFIXES include
  PATHS
  ${CMAKE_SOURCE_DIR}/thirdparty/*
)

MESSAGE("GLEW_INCLUDE_DIRS is ${GLEW_INCLUDE_DIRS}")

FIND_LIBRARY(GLEW_LIBRARIES
  NAMES glew32s glew32
  PATH_SUFFIXES lib64 lib lib32
  PATHS
  ${CMAKE_SOURCE_DIR}/thirdparty/*
)

MESSAGE("GLEW_LIBRARIES is ${GLEW_LIBRARIES}")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLEW DEFAULT_MSG 
                                  GLEW_LIBRARIES
                                  GLEW_INCLUDE_DIRS)
